# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('desc', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('thump', models.ImageField(blank=True, default=b'default.jpeg', upload_to=b'')),
            ],
        ),
    ]
