# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='store',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='store',
            name='thump',
        ),
    ]
