# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20180705_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='prize',
            field=models.IntegerField(default=10, max_length=100),
            preserve_default=False,
        ),
    ]
