# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 13:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0005_auto_20180705_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='store',
            name='thump',
            field=models.ImageField(blank=True, default=b'default.jpeg', upload_to=b''),
        ),
    ]
