# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20180705_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='store',
            name='thump',
        ),
    ]
